title: Echo Server
description: HTTP request/response service for testing and debugging
url: "https://bgarvit01.github.io"
baseurl: "/echoserver"
theme: minima

markdown: kramdown
permalink: pretty

# Header pages navigation order
header_pages:
  - index.md
  - quick-start.md
  - docker.md
  - docker-compose.md
  - kubernetes.md
  - configuration.md
  - feature-toggle.md
  - commands.md

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
